arch:
  - arm64
  
language: cpp
sudo: required

matrix:
  include:
    - name: Ubuntu xenial aarch64 coverage build (no binaries uploaded)
      env: ARCH=aarch64 BUILD_TYPE=coverage
      arch: arm64
      dist: xenial
      addons:
        apt:
          update: true
          packages:
            - libmagic-dev
            - libjpeg-dev
            - libpng-dev
            - cimg-dev
      before_script:
        - sudo pip install gcovr
      script: travis/test-coverage.sh
      after_success: true  # also, we don't intend to upload release binaries
ss: true  # also, we don't intend to upload release binaries

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
